### ISSUE TITLE
Google fonts link has literal ampersand

### ISSUE THREAD

**Issue by rla** [qawemlilo/blog#2]
Both in index.ejs and post.ejs:

https://github.com/qawemlilo/blog/blob/0a9d25b86c318f03d847e044663945b134378b24/template/post.ejs#L15

Should have HTML entity &amp;

Also pointed out by validator:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fblog.ragingflame.co.za%2F

**Comment by qawemlilo** [comment]
Thank you @rla, I have fixed this :+1:
